// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@taskmanager.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tags": {
            "get": {
                "description": "Получение списка всех тегов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Список тегов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.Tag"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создание нового тега",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Создать тег",
                "parameters": [
                    {
                        "description": "Данные тега",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.CreateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.Tag"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/tags/{id}": {
            "get": {
                "description": "Получение тега по идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Получить тег по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID тега",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.Tag"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаление тега по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Удалить тег",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID тега",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "Получение списка задач с возможностью фильтрации и пагинации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Список задач с фильтрацией",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Статус задачи (new, in_progress, done, cancelled)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Дата начала периода (YYYY-MM-DD)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Дата конца периода (YYYY-MM-DD)",
                        "name": "date_to",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Теги для фильтрации",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит записей",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение для пагинации",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.TaskListResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создание новой задачи",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Создать задачу",
                "parameters": [
                    {
                        "description": "Данные задачи",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.Task"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks-period": {
            "get": {
                "description": "Получение списка задач за указанный период",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks-period"
                ],
                "summary": "Получить задачи за период",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Начало периода (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Конец периода (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.TaskListResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создание задачи с указанием периода выполнения",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks-period"
                ],
                "summary": "Создать задачу с периодом",
                "parameters": [
                    {
                        "description": "Данные задачи с периодом",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.CreateTaskPeriodRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.Task"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks-period/{id}": {
            "put": {
                "description": "Установка статуса задачи на конкретную дату",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks-period"
                ],
                "summary": "Установить статус задачи на дату",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Статус задачи",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.SetStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаление переопределения статуса задачи на конкретную дату",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks-period"
                ],
                "summary": "Удалить переопределение статуса задачи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата переопределения (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "Получение задачи по идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Получить задачу по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.Task"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновление существующей задачи",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Обновить задачу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновленные данные задачи",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.UpdateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.Task"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаление задачи по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Удалить задачу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{taskId}/tags": {
            "get": {
                "description": "Получение списка тегов, привязанных к задаче",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Получить теги задачи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.Tag"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{taskId}/tags/{tagId}": {
            "post": {
                "description": "Привязка тега к задаче",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Добавить тег к задаче",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID тега",
                        "name": "tagId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные тега (опционально)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.CreateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Отвязка тега от задачи",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Удалить тег из задачи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID тега",
                        "name": "tagId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID задачи или формат даты",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Переопределение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Vladroon22_TaskTracker_internal_models.BadRequestResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Not found"
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.CreateTagRequest": {
            "type": "object",
            "required": [
                "names"
            ],
            "properties": {
                "names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.CreateTaskPeriodRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "is_recurring": {
                    "type": "boolean"
                },
                "recurrence_days": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "recurrence_interval": {
                    "type": "integer"
                },
                "recurrence_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.CreateTaskRequest": {
            "type": "object",
            "required": [
                "due_date",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "is_recurring": {
                    "type": "boolean"
                },
                "recurrence_days": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "recurrence_interval": {
                    "type": "integer"
                },
                "recurrence_type": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.TaskStatus"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid request body"
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.ServerErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Internal server error"
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.SetStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "done"
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.Tag": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.Task": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_recurring": {
                    "type": "boolean"
                },
                "recurrence_days": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "recurrence_interval": {
                    "type": "integer"
                },
                "recurrence_type": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.TaskStatus"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.Tag"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.TaskListResponse": {
            "type": "object",
            "properties": {
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.Task"
                    }
                }
            }
        },
        "github_com_Vladroon22_TaskTracker_internal_models.TaskStatus": {
            "type": "string",
            "enum": [
                "new",
                "in_progress",
                "done",
                "cancelled"
            ],
            "x-enum-varnames": [
                "StatusNew",
                "StatusInProgress",
                "StatusDone",
                "StatusCancelled"
            ]
        },
        "github_com_Vladroon22_TaskTracker_internal_models.UpdateTaskRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_Vladroon22_TaskTracker_internal_models.TaskStatus"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Управление задачами",
            "name": "tasks"
        },
        {
            "description": "Управление тегами",
            "name": "tags"
        },
        {
            "description": "Задачи с периодами выполнения",
            "name": "tasks-period"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Task Manager API",
	Description:      "API для управления задачами и тегами",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
